FROM node:20-alpine AS base
WORKDIR /app
COPY package*.json ./

FROM base AS dev
RUN npm ci --include=dev
COPY --chown=node:node . .
USER node
EXPOSE 3000
CMD [ "npm", "run", "dev" ]

FROM base AS prod
RUN npm ci --omit=dev
COPY --chown=node:node . .
USER node
EXPOSE 3000
CMD ["node", "app.js"]